Add data_sample function and unit test
anovos/anovos pull request #146
Opened 2022-04-08 00:21 UTC by dattranm

2022-04-20 18:50 UTC, kajanansangar requested changes

2022-04-20 18:50 UTC, kajanansangar commented on src/main/anovos/data_ingest/data_sampling.py
> +):
@dattranm inline comments are missing here, please do add them and let me know

2022-04-20 21:24 UTC, kajanansangar requested changes

2022-04-20 21:24 UTC, kajanansangar commented on src/main/anovos/data_ingest/data_sampling.py
> +        if stratified_type not in ["proportionate", "disproportionate"]:
I would suggest using terms such as "population" & "balanced", "population" meaning stratified sampling outcome follows the population distribution and "balanced" meaning stratified sampling  output follows the balanced distribution based on the strata columns

2022-04-21 23:56 UTC, nisha20verma commented
- Putting sampling function under data_ingest.py instead of a separate module
- fraction, seed, unique_threshold >> “0.5” or 0.5 - both should be ok as long as we can convert the string input into a valid numeric value.
- Check in Line 42 itself if strata col is a categorical column or not,  then Line 44 will be redundant
- Error messaging is not correct if the cardinality is higher than the given threshold.

Suggestions to make coding style consistent in all anovos functions:

- from pyspark.sql.functions import concat, lit >>> Using F.concat, F.lit (just to be consistent with other coding style)
- Using “list_of_cols” instead of “strata_cols” to be consistent with all anovos functions
- Also, we do error handling for invalid input columns in a slightly different manner and it is consistent for all other anovos functions. Maybe you can refer to that.

2022-04-25 16:09 UTC, dattranm commented
@nisha20verma Thanks for the review! I have addressed most of your comments above. For the suggestion, as we discussed, I leave the strata_cols for data_sample function to keep its meaning. I also changed the way to handle errors to somewhat standardize with what we have in anovos. Can you review it again and lmk if anything?

2022-04-26 15:52 UTC, dattranm commented
Thanks for pointing out @sinuochen. I have changed accordingly to make sure only the function check on strata_cols and such only on method_type=='stratified'

2022-05-05 00:17 UTC, merged