Fixing the Pie Chart Issue
anovos/anovos pull request #187
Opened 2022-05-19 08:06 UTC by sourjyasen07

The input data to Pie Chart was not being read properly which was causing it to not populate the chart labels, etc. The latest change addresses the same.

2022-05-19 23:32 UTC, kajanansangar commented
@sourjyas i am getting the following error while running in my local . Refer the log below,

https://justpaste.it/4bwne

2022-05-19 23:33 UTC, kajanansangar requested changes
End to end run is failing https://justpaste.it/4bwne

2022-05-24 20:31 UTC, dattranm commented
@sourjyasen07 Hey! The branch works on Intel chip Mac and doesn't work on M1 Machine. This behavior is likely inherited from Main branch. In details, on M1 machine it stops on report_preprocessing step on my test.

2022-05-27 18:42 UTC, kajanansangar approved these changes

2022-05-27 18:42 UTC, merged