feature/mlflow-integration
anovos/anovos pull request #229
Opened 2022-06-29 08:46 UTC by mathiaspet

This PR contains the first version of an integration of mlflow artifact tracking into Anovos. The outputs, intermediate results and reports/statistics can be logged to a configured server.

2022-06-29 10:18 UTC, ionicsolutions requested changes

2022-06-29 10:18 UTC, ionicsolutions commented on src/main/anovos/data_report/basic_report_generation.py
> +    mlflow_config: dict = None,
For backwards compatibility, please use `Dict` (`from typing import Dict`) and if possible specify the types completely:

```python
from typing import Union, Dict, Any

...

mlflow_config: Union[Dict[str, Any], None] = None
```
```

2022-06-29 10:18 UTC, ionicsolutions commented on src/main/anovos/data_report/report_preprocessing.py
> +    mlflow_config: dict = None,
Same as above

2022-06-29 10:18 UTC, ionicsolutions commented on src/main/anovos/workflow.py
> +def save(data, write_configs, folder_name, reread=False, mlflow_config: dict = None):
Same as above: Fix type specification

2022-06-30 14:19 UTC, ionicsolutions approved these changes

2022-11-25 12:22 UTC, VishnuGowthem approved these changes

2022-11-25 19:04 UTC, merged