optimize measures_of_centralTendency
anovos/anovos pull request #278
Opened 2022-08-22 08:49 UTC by mwjinjin

2022-08-23 18:29 UTC, dattranm requested changes

2022-08-23 18:29 UTC, dattranm commented on src/main/anovos/data_analyzer/stats_generator.py
> +        odf.persist()
It is a good practice to always do `unpersist` after `persist`. Can you add that in here?

2022-08-23 18:29 UTC, dattranm commented on src/main/anovos/data_analyzer/stats_generator.py
>          odf.show(len(list_of_cols))
The same as above. Need to add `unpersist`.

2022-08-24 07:32 UTC, mwjinjin commented
Hi @dattranm , I did several testing on persist() and unpersist(), pls refer to the result here: https://mobilewalla.atlassian.net/browse/AV-505?focusedCommentId=10517. Based on the testing result, doing persist() without unpersist() gives the best performance. Is it acceptable that we keep persist() without unpersist()?

2022-08-24 15:11 UTC, dattranm commented
@mwjinjin It's not always about the runtime here. Whenever you do `persist` on a DataFrame, that DataFrame will stay inside the `persist` option for as long as the Spark Session is still active, thus, will cause memory stress on the Spark session even after this whole function finishes. It is always a good practice to do `unpersist` in order to relieve the memory stress caused by `persist`, else the function/Spark Session will become much more unpredictable and unstable after.

2022-08-24 15:19 UTC, mwjinjin commented
Hi @dattranm , I just removed persist() since I think persist() does not do much help for the performance, and I agree with you that unpersisting is a good practice, thank you!

2022-08-24 15:36 UTC, dattranm commented
Thank @mwjinjin . Will approve and merge once all the tests pass.

2022-08-24 17:40 UTC, dattranm approved these changes

2022-08-24 17:41 UTC, merged