Unique count computation rsd value correction
anovos/anovos pull request #291
Opened 2022-09-08 07:33 UTC by cshekhar17

2022-09-12 19:34 UTC, dattranm requested changes
This `rsd` change is fine. However, can you use this PR to add the value check for `rsd` as well? For example, check type, and value, and such. You can refer to https://github.com/anovos/anovos/blob/dd553da3d2fc2ba0207a6e08d993a481743525ca/src/main/anovos/data_ingest/data_ingest.py#L128 for example.

2022-09-22 17:55 UTC, dattranm requested changes
The `rsd` default value you leave it as `None`, so when it is compared with 0, it gives an error in the unit test, as `None` cannot be compared with 0, `NoneType` v. `int`. You will need to exclude the `None` when doing the input check.

Also, does `rsd` have any upper limit value?

2022-09-26 15:00 UTC, dattranm approved these changes
Every comment and concern has been addressed. This PR is good to merge now. @kajanansangar can you have a final look and merge?

2022-09-28 20:27 UTC, kajanansangar approved these changes

2022-09-28 20:28 UTC, merged