Feature Recommender minor structure changes
anovos/anovos pull request #97
Opened 2022-02-23 21:48 UTC by dattranm

Change to way calling model and input dataframe:
- Create functions to wrap all the data process steps inside
- Create function to call the model implicitly instead of explicitly
- Properly structure the featrec_init to for both feature_exploration and feature_recommendation

2022-02-24 09:10 UTC, ionicsolutions requested changes
Thanks for addressing the issue, I've added a suggestion to introduce proper lazy loading

2022-02-24 09:10 UTC, ionicsolutions commented on src/main/anovos/feature_recommender/featrec_init.py
> +warnings.filterwarnings("ignore")
```suggestion
```

Please don't hide warnings in library code. If a user doesn't want to see warnings, they can suppress them further up in their own code.

2022-02-24 09:10 UTC, ionicsolutions commented on src/main/anovos/feature_recommender/featrec_init.py
> +    return model
```suggestion
class _TransformerModel:
    def __init__(self):
        self._model = None

    @property
    def model(self) -> SentenceTransformer:
        if self._model is None:
            self._model = SentenceTransformer("all-mpnet-base-v2")
        return self._model

model = _TransformerModel()
```

I wouldn't load the model every time, but exactly once. Loading such a huge model even from disk can cause significant delay.

2022-02-24 09:10 UTC, ionicsolutions commented on src/main/anovos/feature_recommender/featrec_init.py
> +    model_fer = init_model()
```suggestion
```

See above, no need to load the model every time

2022-02-24 09:10 UTC, ionicsolutions commented on src/main/anovos/feature_recommender/featrec_init.py
> +    list_embedding_train_fer = model_fer.encode(list_train_fer, convert_to_tensor=True)
```suggestion
    list_embedding_train_fer = model.model.encode(list_train_fer, convert_to_tensor=True)
```

2022-02-24 18:57 UTC, dattranm commented
Thanks @ionicsolutions . All of your suggested changes have been committed, including model lazy load and remove the ignore warnings.

2022-02-24 23:47 UTC, kajanansangar commented on src/main/anovos/feature_recommender/feature_recommendation.py
>                                  "Null",
Null should be replaced with NA as discussed
<img width="903" alt="Screenshot 2022-02-24 at 6 46 09 PM" src="https://user-images.githubusercontent.com/92550461/155626413-bfa79494-9f59-4065-81a1-442e276cc787.png">
.

2022-02-25 22:19 UTC, dattranm commented
@ionicsolutions Regarding to Issue #94, I have implemented model_download function for feature recommender, as well as cache check for model path in user local. Can you review it and lmk if anything? Thank you so much!

2022-02-28 15:23 UTC, ionicsolutions approved these changes

2022-02-28 20:49 UTC, kajanansangar approved these changes

2022-02-28 23:21 UTC, merged